//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPLAN_API.ServiceReference1 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ZCvReadSalesConf.RfcException", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZCvReadSalesConfRfcException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZCvReadSalesConfRfcExceptions nameField;
        
        private string textField;
        
        private RfcExceptionMessage messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZCvReadSalesConfRfcExceptions Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public RfcExceptionMessage Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ZCvReadSalesConf.RfcExceptions", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public enum ZCvReadSalesConfRfcExceptions {
        
        /// <remarks/>
        ItemNotConfigurable,
        
        /// <remarks/>
        ItemNotFound,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RfcException.Message", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class RfcExceptionMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ConfOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string atinnField;
        
        private string atnamField;
        
        private string atbezField;
        
        private string atwrtField;
        
        private string atwtbField;
        
        private float ewahrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Atinn {
            get {
                return this.atinnField;
            }
            set {
                this.atinnField = value;
                this.RaisePropertyChanged("Atinn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Atnam {
            get {
                return this.atnamField;
            }
            set {
                this.atnamField = value;
                this.RaisePropertyChanged("Atnam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Atbez {
            get {
                return this.atbezField;
            }
            set {
                this.atbezField = value;
                this.RaisePropertyChanged("Atbez");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Atwrt {
            get {
                return this.atwrtField;
            }
            set {
                this.atwrtField = value;
                this.RaisePropertyChanged("Atwrt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Atwtb {
            get {
                return this.atwtbField;
            }
            set {
                this.atwtbField = value;
                this.RaisePropertyChanged("Atwtb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public float Ewahr {
            get {
                return this.ewahrField;
            }
            set {
                this.ewahrField = value;
                this.RaisePropertyChanged("Ewahr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="ServiceReference1.Z_CV_READ_SALES_CONF")]
    public interface Z_CV_READ_SALES_CONF {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ZCvReadSalesConf no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(EPLAN_API.ServiceReference1.ZCvReadSalesConfRfcException), Action="", Name="ZCvReadSalesConf.Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EPLAN_API.ServiceReference1.ZCvReadSalesConfResponse1 ZCvReadSalesConf(EPLAN_API.ServiceReference1.ZCvReadSalesConfRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EPLAN_API.ServiceReference1.ZCvReadSalesConfResponse1> ZCvReadSalesConfAsync(EPLAN_API.ServiceReference1.ZCvReadSalesConfRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZCvReadSalesConf : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDocumentNumberField;
        
        private string iItemNumberField;
        
        private string iLangField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IDocumentNumber {
            get {
                return this.iDocumentNumberField;
            }
            set {
                this.iDocumentNumberField = value;
                this.RaisePropertyChanged("IDocumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IItemNumber {
            get {
                return this.iItemNumberField;
            }
            set {
                this.iItemNumberField = value;
                this.RaisePropertyChanged("IItemNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ILang {
            get {
                return this.iLangField;
            }
            set {
                this.iLangField = value;
                this.RaisePropertyChanged("ILang");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZCvReadSalesConfResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ConfOut[] configurationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ConfOut[] Configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
                this.RaisePropertyChanged("Configuration");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZCvReadSalesConfRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public EPLAN_API.ServiceReference1.ZCvReadSalesConf ZCvReadSalesConf;
        
        public ZCvReadSalesConfRequest() {
        }
        
        public ZCvReadSalesConfRequest(EPLAN_API.ServiceReference1.ZCvReadSalesConf ZCvReadSalesConf) {
            this.ZCvReadSalesConf = ZCvReadSalesConf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZCvReadSalesConfResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public EPLAN_API.ServiceReference1.ZCvReadSalesConfResponse ZCvReadSalesConfResponse;
        
        public ZCvReadSalesConfResponse1() {
        }
        
        public ZCvReadSalesConfResponse1(EPLAN_API.ServiceReference1.ZCvReadSalesConfResponse ZCvReadSalesConfResponse) {
            this.ZCvReadSalesConfResponse = ZCvReadSalesConfResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Z_CV_READ_SALES_CONFChannel : EPLAN_API.ServiceReference1.Z_CV_READ_SALES_CONF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Z_CV_READ_SALES_CONFClient : System.ServiceModel.ClientBase<EPLAN_API.ServiceReference1.Z_CV_READ_SALES_CONF>, EPLAN_API.ServiceReference1.Z_CV_READ_SALES_CONF {
        
        public Z_CV_READ_SALES_CONFClient() {
        }
        
        public Z_CV_READ_SALES_CONFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Z_CV_READ_SALES_CONFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_CV_READ_SALES_CONFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Z_CV_READ_SALES_CONFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EPLAN_API.ServiceReference1.ZCvReadSalesConfResponse1 EPLAN_API.ServiceReference1.Z_CV_READ_SALES_CONF.ZCvReadSalesConf(EPLAN_API.ServiceReference1.ZCvReadSalesConfRequest request) {
            return base.Channel.ZCvReadSalesConf(request);
        }
        
        public EPLAN_API.ServiceReference1.ZCvReadSalesConfResponse ZCvReadSalesConf(EPLAN_API.ServiceReference1.ZCvReadSalesConf ZCvReadSalesConf1) {
            EPLAN_API.ServiceReference1.ZCvReadSalesConfRequest inValue = new EPLAN_API.ServiceReference1.ZCvReadSalesConfRequest();
            inValue.ZCvReadSalesConf = ZCvReadSalesConf1;
            EPLAN_API.ServiceReference1.ZCvReadSalesConfResponse1 retVal = ((EPLAN_API.ServiceReference1.Z_CV_READ_SALES_CONF)(this)).ZCvReadSalesConf(inValue);
            return retVal.ZCvReadSalesConfResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EPLAN_API.ServiceReference1.ZCvReadSalesConfResponse1> EPLAN_API.ServiceReference1.Z_CV_READ_SALES_CONF.ZCvReadSalesConfAsync(EPLAN_API.ServiceReference1.ZCvReadSalesConfRequest request) {
            return base.Channel.ZCvReadSalesConfAsync(request);
        }
        
        public System.Threading.Tasks.Task<EPLAN_API.ServiceReference1.ZCvReadSalesConfResponse1> ZCvReadSalesConfAsync(EPLAN_API.ServiceReference1.ZCvReadSalesConf ZCvReadSalesConf) {
            EPLAN_API.ServiceReference1.ZCvReadSalesConfRequest inValue = new EPLAN_API.ServiceReference1.ZCvReadSalesConfRequest();
            inValue.ZCvReadSalesConf = ZCvReadSalesConf;
            return ((EPLAN_API.ServiceReference1.Z_CV_READ_SALES_CONF)(this)).ZCvReadSalesConfAsync(inValue);
        }
    }
}
